In [100]:
## Loading Libraries
import pandas as pd
import numpy as np
import sys
import jdatetime as jd
import os
import pickle
import io
from scipy.stats import ttest_ind

# import power_index_calculator as px
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# **Loading Data**

In [188]:
os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM")
Data = pd.read_csv('Data.csv')
cond = np.logical_and(Data.year>=1389, Data.year<=1397)
Data = Data[cond]

In [189]:
OCM = ['largest_owner','first_second', 'first_sumtwofour', 'sumfive', 'gini',
       'herfindahl','sscl', 'ssco', 'ssdl', 'ssdo', 'bzcl', 'bzco', 'bzdl']

Vars = ['marketcap','payout', 'DIVTOI', 'DIVTNI', 'DIVTEQ', 'DIVTS', 'DPAY',
        'DIVTMVE', 'ROA', 'ROE', 'DLOSS', 'NPLOSS', 'MTB', 'LEVRG', 'LNTA','LNQ']

describe_columns = [('above_meadian','')]+list(zip(Vars,['mean']*len(Vars)))

In [190]:
def find_significant(p,val):
    if p>0.1 or pd.isnull(p):
        return(str(val))
    elif p>0.05:
        return(str(val)+'*')
    elif p>0.01:
        return(str(val)+'**')
    else:
        return(str(val)+'***')

# **Table of Differences**

In [203]:
iterables = [Vars, ['High', 'Low','diff','p_value']]
col_index = pd.MultiIndex.from_product(iterables)
out = pd.DataFrame(index=OCM,columns=col_index)

for ocm in OCM:     
        
    df = Data.copy()
    meadian = df[ocm].describe()['50%']
    df['above_meadian'] = df[ocm]>meadian
    df = df[~pd.isnull(df.above_meadian)]
    
    
    for var in Vars:
        temp = df[~pd.isnull(df[var])]
        temp =df
        serie1 = temp[temp.above_meadian][var]
        high = np.round(np.mean(serie1),3)
        
        serie2 = temp[~temp.above_meadian][var]
        low = np.round(np.mean(serie2),3)
        
        (t,p) = ttest_ind(serie1,serie2,nan_policy='omit')
        
        diff = find_significant(p,np.round(high-low,3))
        
        out.loc[ocm,(var,)] = [high,low,diff,np.round(p,2)]

        
out

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\async_helpers.py:68: PerformanceWarning: indexing past lexsort depth may impact performance.
  coro.send(None)

                    marketcap                                        payout  \
                         High          Low              diff p_value   High
largest_owner     1.14073e+07  2.48543e+07  -13447062.804***       0  0.599
first_second      7.91605e+06  2.83774e+07   -20461381.64***       0  0.566
first_sumtwofour  8.15944e+06  2.82332e+07   -20073727.71***       0  0.571
sumfive           1.80746e+07  1.80762e+07         -1640.133       1  0.639
gini              1.10049e+07   2.5227e+07  -14222092.366***       0  0.604
herfindahl        1.14572e+07   2.4855e+07  -13397841.981***       0   0.61
sscl              1.14088e+07  2.49046e+07  -13495777.167***       0  0.598
ssco              2.46181e+07  1.18008e+07   12817295.761***       0  0.548
ssdl              1.14159e+07  2.48628e+07  -13446952.049***       0  0.599
ssdo              2.44811e+07  1.20404e+07   12440651.578***       0  0.547
bzcl                      NaN  1.80754e+07               nan     NaN    NaN
bzco              2.74356e+07  1.07753e+07   16660274.093***       0  0.571
bzdl                      NaN  1.80754e+07               nan     NaN    NaN

                                          DIVTOI         ...   LEVRG          \
                    Low      diff p_value   High    Low  ...    diff p_value
largest_owner     0.553     0.046    0.27  0.462  0.583  ...  -0.007    0.76
first_second      0.587    -0.021    0.62  0.438  0.608  ...  -0.003    0.91
first_sumtwofour  0.582    -0.011    0.79  0.445  0.601  ...  -0.021    0.34
sumfive           0.512  0.127***       0  0.515  0.529  ...  -0.005    0.83
gini              0.548     0.056    0.18  0.483  0.561  ...  -0.021    0.36
herfindahl        0.542     0.068     0.1  0.475  0.569  ...   0.009    0.68
sscl              0.554     0.044     0.3  0.461  0.585  ...  -0.007    0.75
ssco              0.603    -0.055    0.19  0.578  0.468  ...   0.008    0.73
ssdl              0.554     0.045    0.28  0.462  0.584  ...  -0.005     0.8
ssdo              0.604    -0.057    0.17  0.579  0.469  ...   0.011    0.63
bzcl              0.576       nan     NaN    NaN  0.522  ...     nan     NaN
bzco               0.58    -0.009    0.82  0.585  0.473  ...  -0.004    0.86
bzdl              0.576       nan     NaN    NaN  0.522  ...     nan     NaN

                    LNTA                               LNQ                   \
                    High     Low       diff p_value   High    Low      diff
largest_owner     14.249  14.459    -0.21**    0.01  1.329  1.226    0.103*
first_second      14.085  14.626  -0.541***       0  1.265  1.294    -0.029
first_sumtwofour  14.037  14.676  -0.639***       0  1.285  1.274     0.011
sumfive           14.548  14.153   0.395***       0  1.333  1.224    0.109*
gini              14.171   14.54  -0.369***       0  1.285  1.274     0.011
herfindahl        14.272  14.436   -0.164**    0.04  1.347  1.207    0.14**
sscl              14.252  14.457   -0.205**    0.01  1.329  1.226    0.103*
ssco              14.457  14.253    0.204**    0.01  1.209  1.343  -0.134**
ssdl              14.251  14.458   -0.207**    0.01  1.329  1.226    0.103*
ssdo              14.434  14.277     0.157*    0.06  1.226  1.327   -0.101*
bzcl                 NaN  14.353        nan     NaN    NaN  1.279       nan
bzco              14.554  14.197   0.357***       0  1.228  1.318     -0.09
bzdl                 NaN  14.353        nan     NaN    NaN  1.279       nan


                 p_value
largest_owner       0.07
first_second        0.61
first_sumtwofour    0.85
sumfive             0.05
gini                0.85
herfindahl          0.01
sscl                0.07
ssco                0.02
ssdl                0.07
ssdo                0.07
bzcl                 NaN
bzco                0.12
bzdl                 NaN

[13 rows x 64 columns]

## Latex Output

In [209]:
for var in Vars:
    temp = out[(var,)]

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                         High          Low              diff p_value
largest_owner     1.14073e+07  2.48543e+07  -13447062.804***       0
first_second      7.91605e+06  2.83774e+07   -20461381.64***       0
first_sumtwofour  8.15944e+06  2.82332e+07   -20073727.71***       0
sumfive           1.80746e+07  1.80762e+07         -1640.133       1
gini              1.10049e+07   2.5227e+07  -14222092.366***       0
herfindahl        1.14572e+07   2.4855e+07  -13397841.981***       0
sscl              1.14088e+07  2.49046e+07  -13495777.167***       0
ssco              2.46181e+07  1.18008e+07   12817295.761***       0
ssdl              1.14159e+07  2.48628e+07  -13446952.049***       0
ssdo              2.44811e+07  1.20404e+07   12440651.578***       0
bzcl                      NaN  1.80754e+07               nan     NaN
bzco              2.74356e+07  1.07753e+07   16660274.093***       0
bzdl                      NaN  1.80754e+07               nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low      diff p_value
largest_owner     0.599  0.553     0.046    0.27
first_second      0.566  0.587    -0.021    0.62
first_sumtwofour  0.571  0.582    -0.011    0.79
sumfive           0.639  0.512  0.127***       0
gini              0.604  0.548     0.056    0.18
herfindahl         0.61  0.542     0.068     0.1
sscl              0.598  0.554     0.044     0.3
ssco              0.548  0.603    -0.055    0.19
ssdl              0.599  0.554     0.045    0.28
ssdo              0.547  0.604    -0.057    0.17
bzcl                NaN  0.576       nan     NaN
bzco              0.571   0.58    -0.009    0.82
bzdl                NaN  0.576       nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low     diff p_value
largest_owner     0.462  0.583   -0.121    0.19
first_second      0.438  0.608   -0.17*    0.06
first_sumtwofour  0.445  0.601  -0.156*    0.09
sumfive           0.515  0.529   -0.014    0.88
gini              0.483  0.561   -0.078     0.4
herfindahl        0.475  0.569   -0.094    0.31
sscl              0.461  0.585   -0.124    0.18
ssco              0.578  0.468     0.11    0.23
ssdl              0.462  0.584   -0.122    0.19
ssdo              0.579  0.469     0.11    0.23
bzcl                NaN  0.522      nan     NaN
bzco              0.585  0.473    0.112    0.23
bzdl                NaN  0.522      nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner     0.788  0.908      -0.12    0.15
first_second      0.735  0.962  -0.227***    0.01
first_sumtwofour  0.739  0.958  -0.219***    0.01
sumfive             0.9  0.796      0.104    0.22
gini              0.829  0.867     -0.038    0.66
herfindahl        0.824  0.873     -0.049    0.56
sscl              0.786  0.911     -0.125    0.14
ssco              0.907  0.791      0.116    0.17
ssdl              0.787  0.909     -0.122    0.15
ssdo              0.905  0.794      0.111    0.19
bzcl                NaN  0.848        nan     NaN
bzco               0.94  0.776     0.164*    0.05
bzdl                NaN  0.848        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner     0.196  0.183      0.013    0.19
first_second      0.162  0.218  -0.056***       0
first_sumtwofour  0.163  0.217  -0.054***       0
sumfive           0.235  0.144   0.091***       0
gini              0.185  0.195      -0.01    0.32
herfindahl        0.207  0.172   0.035***       0
sscl              0.195  0.184      0.011    0.24
ssco              0.178  0.201   -0.023**    0.02
ssdl              0.196  0.183      0.013    0.21
ssdo              0.179  0.199    -0.02**    0.04
bzcl                NaN   0.19        nan     NaN
bzco              0.192  0.188      0.004    0.72
bzdl                NaN   0.19        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low    diff p_value
largest_owner     0.175  0.179  -0.004    0.86
first_second      0.166  0.188  -0.022    0.27
first_sumtwofour   0.17  0.183  -0.013    0.51
sumfive           0.173   0.18  -0.007    0.72
gini              0.177  0.177     0.0    0.98
herfindahl        0.175  0.179  -0.004    0.81
sscl              0.175  0.179  -0.004    0.83
ssco              0.174  0.179  -0.005    0.79
ssdl              0.175  0.179  -0.004    0.84
ssdo              0.172  0.181  -0.009    0.63
bzcl                NaN  0.177     nan     NaN
bzco               0.19  0.167   0.023    0.25
bzdl                NaN  0.177     nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner     0.813  0.816     -0.003    0.89
first_second       0.79  0.839  -0.049***    0.01
first_sumtwofour  0.793  0.837   -0.044**    0.02
sumfive           0.857  0.772   0.085***       0
gini              0.819   0.81      0.009    0.66
herfindahl        0.818  0.812      0.006    0.75
sscl              0.813  0.816     -0.003    0.85
ssco              0.813  0.816     -0.003     0.9
ssdl              0.812  0.817     -0.005    0.81
ssdo               0.81  0.819     -0.009    0.66
bzcl                NaN  0.815        nan     NaN
bzco               0.82  0.811      0.009    0.64
bzdl                NaN  0.815        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner      0.07  0.071     -0.001    0.98
first_second      0.064  0.077  -0.013***       0
first_sumtwofour  0.064  0.077  -0.013***       0
sumfive           0.077  0.064   0.013***       0
gini               0.07  0.071     -0.001    0.85
herfindahl        0.072  0.069      0.003     0.4
sscl               0.07  0.071     -0.001    0.91
ssco               0.07  0.071     -0.001    0.76
ssdl               0.07  0.071     -0.001    0.94
ssdo              0.069  0.072     -0.003    0.57
bzcl                NaN  0.071        nan     NaN
bzco              0.073  0.069      0.004     0.3
bzdl                NaN  0.071        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner     0.144  0.142      0.002    0.73
first_second      0.128  0.159  -0.031***       0
first_sumtwofour   0.13  0.157  -0.027***       0
sumfive            0.17  0.116   0.054***       0
gini              0.142  0.144     -0.002    0.77
herfindahl        0.148  0.138       0.01    0.21
sscl              0.145  0.142      0.003    0.72
ssco              0.138  0.148      -0.01    0.21
ssdl              0.144  0.142      0.002    0.75
ssdo              0.139  0.146     -0.007    0.36
bzcl                NaN  0.143        nan     NaN
bzco              0.143  0.143        0.0    0.95
bzdl                NaN  0.143        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low    diff p_value
largest_owner     0.361  0.304   0.057    0.35
first_second       0.31  0.357  -0.047    0.45
first_sumtwofour  0.314  0.353  -0.039    0.52
sumfive           0.372  0.294   0.078     0.2
gini              0.377  0.288   0.089    0.15
herfindahl        0.364  0.301   0.063    0.31
sscl              0.358  0.308    0.05    0.41
ssco              0.292  0.372   -0.08    0.19
ssdl              0.358  0.308    0.05    0.41
ssdo              0.327  0.339  -0.012    0.84
bzcl                NaN  0.333     nan     NaN
bzco              0.312  0.349  -0.037    0.55
bzdl                NaN  0.333     nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner     0.112  0.113     -0.001    0.98
first_second      0.138  0.087   0.051***       0
first_sumtwofour  0.136  0.089   0.047***       0
sumfive           0.075   0.15  -0.075***       0
gini              0.112  0.113     -0.001    0.94
herfindahl        0.116   0.11      0.006     0.7
sscl              0.112  0.113     -0.001    0.94
ssco              0.113  0.112      0.001    0.95
ssdl              0.112  0.113     -0.001    0.97
ssdo              0.114  0.111      0.003    0.84
bzcl                NaN  0.113        nan     NaN
bzco               0.11  0.114     -0.004    0.79
bzdl                NaN  0.113        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low       diff p_value
largest_owner     0.117  0.125     -0.008    0.64
first_second      0.147  0.095   0.052***       0
first_sumtwofour  0.147  0.095   0.052***       0
sumfive           0.088  0.154  -0.066***       0
gini              0.124  0.118      0.006    0.71
herfindahl        0.119  0.123     -0.004    0.82
sscl              0.117  0.125     -0.008     0.6
ssco              0.126  0.116       0.01     0.5
ssdl              0.117  0.125     -0.008    0.63
ssdo              0.129  0.113      0.016    0.34
bzcl                NaN  0.121        nan     NaN
bzco              0.118  0.123     -0.005    0.78
bzdl                NaN  0.121        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low      diff p_value
largest_owner     7.478  5.461     2.017    0.11
first_second      7.819  5.129    2.69**    0.03
first_sumtwofour  7.258  5.696     1.562    0.22
sumfive           6.739  6.237     0.502    0.69
gini              7.023  5.938     1.085    0.39
herfindahl        7.726  5.199   2.527**    0.05
sscl              7.255  5.688     1.567    0.22
ssco              5.162  7.731  -2.569**    0.04
ssdl              7.256  5.691     1.565    0.22
ssdo              5.674  7.241    -1.567    0.22
bzcl                NaN   6.49       nan     NaN
bzco              5.613  7.165    -1.552    0.23
bzdl                NaN   6.49       nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low    diff p_value
largest_owner     0.588  0.595  -0.007    0.76
first_second       0.59  0.593  -0.003    0.91
first_sumtwofour  0.581  0.602  -0.021    0.34
sumfive           0.589  0.594  -0.005    0.83
gini              0.581  0.602  -0.021    0.36
herfindahl        0.596  0.587   0.009    0.68
sscl              0.588  0.595  -0.007    0.75
ssco              0.596  0.588   0.008    0.73
ssdl              0.589  0.594  -0.005     0.8
ssdo              0.597  0.586   0.011    0.63
bzcl                NaN  0.592     nan     NaN
bzco              0.589  0.593  -0.004    0.86
bzdl                NaN  0.592     nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                    High     Low       diff p_value
largest_owner     14.249  14.459    -0.21**    0.01
first_second      14.085  14.626  -0.541***       0
first_sumtwofour  14.037  14.676  -0.639***       0
sumfive           14.548  14.153   0.395***       0
gini              14.171   14.54  -0.369***       0
herfindahl        14.272  14.436   -0.164**    0.04
sscl              14.252  14.457   -0.205**    0.01
ssco              14.457  14.253    0.204**    0.01
ssdl              14.251  14.458   -0.207**    0.01
ssdo              14.434  14.277     0.157*    0.06
bzcl                 NaN  14.353        nan     NaN
bzco              14.554  14.197   0.357***       0
bzdl                 NaN  14.353        nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low      diff p_value
largest_owner     1.329  1.226    0.103*    0.07
first_second      1.265  1.294    -0.029    0.61
first_sumtwofour  1.285  1.274     0.011    0.85
sumfive           1.333  1.224    0.109*    0.05
gini              1.285  1.274     0.011    0.85
herfindahl        1.347  1.207    0.14**    0.01
sscl              1.329  1.226    0.103*    0.07
ssco              1.209  1.343  -0.134**    0.02
ssdl              1.329  1.226    0.103*    0.07
ssdo              1.226  1.327   -0.101*    0.07
bzcl                NaN  1.279       nan     NaN
bzco              1.228  1.318     -0.09    0.12
bzdl                NaN  1.279       nan     NaN