In [12]:
## Loading Libraries
import pandas as pd
import numpy as np
import sys
import jdatetime as jd
import os
import pickle
import io
from scipy import stats
from scipy.stats import ttest_ind
from scipy.stats import median_test


# import power_index_calculator as px
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from find_significant import find_significant

In [17]:
stat,p,m,table = median_test(Data.sscl,Data.ssdl,ties='above',nan_policy='omit')
stat,p,m,table

(0.14689808042692354,
 0.701517464865618,
 0.9927459999999999,
 array([[1235, 1247],
        [1249, 1232]], dtype=int64))

# **Loading Data**

In [2]:
os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM")
Data = pd.read_csv('Data.csv')
cond = np.logical_and(Data.year>=1389, Data.year<=1397)
Data = Data[cond]

In [11]:
OCM = ['sum_over1','sumfive','sumfour','sumthree','sumtwo','largest_owner','first_second',
       'first_sumtwofour', 'gini','herfindahl','sscl', 'ssco', 'ssdl', 'ssdo', 'bzcl', 'bzco', 'bzdl']

Vars = ['marketcap','payout', 'DIVTOI', 'DIVTNI', 'DIVTEQ', 'DIVTS', 'DPAY',
        'DIVTMVE', 'ROA', 'ROE', 'DLOSS', 'NPLOSS', 'MTB', 'LEVRG', 'LNTA','LNQ']

describe_columns = [('above_meadian','')]+list(zip(Vars,['mean']*len(Vars)))

# **Univariate Analysis**

In [29]:
%%time
iterables = [Vars, ['High', 'Low','diff','p_value']]
col_index = pd.MultiIndex.from_product(iterables)
out = pd.DataFrame(index=OCM,columns=col_index)

for ocm in OCM:     
        
    df = Data.copy()
    
    meadian = df[ocm].describe()['50%']
    df['above_meadian'] = df[ocm]>meadian
    df = df[~pd.isnull(df.above_meadian)]
    
    
    for var in Vars:
        
        temp = df[~pd.isnull(df[var])]
        temp =df
        serie1 = temp[temp.above_meadian][var]
        high = np.round(np.mean(serie1),3)
        
        serie2 = temp[~temp.above_meadian][var]
        low = np.round(np.mean(serie2),3)
        
        (t,p) = ttest_ind(serie1,serie2,nan_policy='omit')
        
        diff = find_significant(p,np.round(high-low,3))
        
        out.loc[ocm,(var,)] = [high,low,diff,np.round(p,2)]

        
out

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2362: PerformanceWarning: indexing past lexsort depth may impact performance.
  result = fn(*args, **kwargs)

Wall time: 6.12 s

                    marketcap                                        payout  \
                         High          Low              diff p_value   High
sum_over1         2.20643e+07  1.52387e+07      6825561.038*    0.06  0.669
sumfive           2.18724e+07   1.5441e+07      6431346.869*    0.07  0.661
sumfour              2.01e+07  1.72549e+07       2845033.674    0.43  0.653
sumthree          1.60007e+07  2.14456e+07      -5444951.618    0.13  0.644
sumtwo            1.39143e+07  2.35941e+07   -9679802.823***    0.01  0.629
largest_owner      1.2313e+07  2.52132e+07  -12900200.806***       0  0.612
first_second      1.10563e+07  2.63776e+07  -15321281.468***       0  0.575
first_sumtwofour  9.52081e+06  2.78278e+07  -18306991.831***       0  0.571
gini              1.20678e+07  2.53372e+07  -13269380.346***       0  0.607
herfindahl        1.24494e+07  2.51068e+07  -12657437.093***       0  0.627
sscl               1.2313e+07  2.52132e+07  -12900200.806***       0  0.612
ssco              2.52617e+07  1.25883e+07   12673433.755***       0  0.529
ssdl              1.23254e+07  2.51672e+07  -12841784.075***       0  0.614
ssdo              2.53656e+07  1.26911e+07   12674529.912***       0  0.529
bzcl                      NaN  1.86939e+07               nan     NaN    NaN
bzco              2.74901e+07  1.17663e+07   15723773.804***       0  0.541
bzdl                      NaN  1.86939e+07               nan     NaN    NaN

                                           DIVTOI         ...   LEVRG          \
                    Low       diff p_value   High    Low  ...    diff p_value
sum_over1         0.479    0.19***       0  0.641  0.433  ...  -0.027    0.15
sumfive           0.488   0.173***       0   0.61  0.466  ...   -0.02     0.3
sumfour           0.497   0.156***       0  0.552  0.527  ...  -0.017    0.38
sumthree          0.506   0.138***       0  0.588   0.49  ...  -0.013    0.49
sumtwo             0.52   0.109***       0  0.565  0.513  ...  -0.003    0.91
largest_owner     0.538    0.074**    0.02  0.544  0.535  ...  -0.011    0.56
first_second      0.577     -0.002    0.94  0.534  0.546  ...  -0.021    0.28
first_sumtwofour  0.581      -0.01    0.75  0.498  0.581  ...  -0.019    0.35
gini              0.544    0.063**    0.05  0.523  0.557  ...  -0.024    0.22
herfindahl        0.523   0.104***       0  0.567   0.51  ...  -0.003     0.9
sscl              0.538    0.074**    0.02  0.544  0.535  ...  -0.011    0.56
ssco              0.618  -0.089***    0.01  0.521  0.556  ...   0.015    0.44
ssdl              0.537    0.077**    0.02  0.544  0.535  ...  -0.011    0.56
ssdo              0.618  -0.089***    0.01  0.523  0.554  ...   0.017    0.38
bzcl              0.576        nan     NaN    NaN   0.54  ...     nan     NaN
bzco              0.603    -0.062*    0.06   0.51  0.562  ...   0.003     0.9
bzdl              0.576        nan     NaN    NaN   0.54  ...     nan     NaN

                    LNTA                               LNQ                    \
                    High     Low       diff p_value   High    Low       diff
sum_over1         14.627  14.059   0.568***       0  1.271  1.249      0.022
sumfive            14.57  14.117   0.453***       0  1.299  1.219      0.08*
sumfour           14.532  14.155   0.377***       0  1.305  1.213    0.092**
sumthree          14.448  14.241   0.207***       0  1.294  1.224       0.07
sumtwo            14.365  14.326      0.039    0.56  1.317    1.2    0.117**
largest_owner     14.257  14.437   -0.18***    0.01  1.311  1.206    0.105**
first_second      14.139  14.557  -0.418***       0   1.26   1.26        0.0
first_sumtwofour  14.068  14.626  -0.558***       0  1.269  1.251      0.018
gini              14.245  14.448  -0.203***       0   1.27   1.25       0.02
herfindahl        14.312  14.381     -0.069    0.31  1.311  1.206    0.105**
sscl              14.257  14.437   -0.18***    0.01  1.311  1.206    0.105**
ssco              14.425  14.273    0.152**    0.03  1.189  1.323  -0.134***
ssdl              14.254   14.44  -0.186***    0.01  1.312  1.205    0.107**
ssdo              14.415  14.285      0.13*    0.06  1.206  1.306     -0.1**
bzcl                 NaN  14.346        nan     NaN    NaN   1.26        nan
bzco              14.502  14.224   0.278***       0  1.203  1.303     -0.1**
bzdl                 NaN  14.346        nan     NaN    NaN   1.26        nan


                 p_value
sum_over1           0.64
sumfive             0.08
sumfour             0.05
sumthree            0.12
sumtwo              0.01
largest_owner       0.02
first_second        0.99
first_sumtwofour    0.71
gini                0.67
herfindahl          0.02
sscl                0.02
ssco                   0
ssdl                0.02
ssdo                0.03
bzcl                 NaN
bzco                0.03
bzdl                 NaN

[17 rows x 64 columns]

In [30]:
out[('DIVTOI',)]

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                   High    Low     diff p_value
sum_over1         0.641  0.433  0.208**    0.02
sumfive            0.61  0.466    0.144    0.11
sumfour           0.552  0.527    0.025    0.79
sumthree          0.588   0.49    0.098    0.28
sumtwo            0.565  0.513    0.052    0.57
largest_owner     0.544  0.535    0.009    0.92
first_second      0.534  0.546   -0.012     0.9
first_sumtwofour  0.498  0.581   -0.083    0.36
gini              0.523  0.557   -0.034    0.71
herfindahl        0.567   0.51    0.057    0.53
sscl              0.544  0.535    0.009    0.92
ssco              0.521  0.556   -0.035     0.7
ssdl              0.544  0.535    0.009    0.91
ssdo              0.523  0.554   -0.031    0.73
bzcl                NaN   0.54      nan     NaN
bzco               0.51  0.562   -0.052    0.57
bzdl                NaN   0.54      nan     NaN

## Latex Output

In [32]:
index = ['Sum_over1','Sumfive','Sumfour','Sumthree','Sumtwo','Largest Owner','First/Second',
         'First/Sumtwofour', 'Gini','Herfindahl','SSCL', 'SSCO', 'SSDL', 'SSDO', 'BZCL', 'BZCO', 'BZDL']

out['OCM'] = index
out.set_index('OCM',inplace=True)

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM\Vars and OCM Meadian\PythonTex")
for var in Vars:
    temp = out[(var,)]
    
    file_name = var+'.tex'
    caption = var+' for Two Groups of Above and Below Meadian'
    
    temp.to_latex(file_name,index=True,multirow=True,
             bold_rows=True,caption=caption)

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

# **Regression Analysis**

In [30]:
# These Two file are creatied using the do-file "Regressions and OCM-1.do" in
# "C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM\Vars and OCM Meadian"

col_names = ["DIVTOI", "DIVTNI", "DIVTS"]
row_index = ["largest_owner", "first_second", "first_sumtwofour", "sumfive", "herfindahl",
             "gini", "sscl", "ssco", "ssdl", "ssdo", "bzcl", "bzco", "bzdl"]

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM\Vars and OCM Meadian")
Coef = pd.read_excel('Coefs.xlsx',header=None,sheet_name='Coef',names=col_names)
Coef['row_index'] = row_index
Coef = Coef.set_index('row_index')

p_val = pd.read_excel('Coefs.xlsx',header=None,sheet_name='p_val',names=col_names)
p_val['row_index'] = row_index
p_val = p_val.set_index('row_index')

In [34]:
out = pd.DataFrame(index=row_index,columns=col_names)
for row in row_index:
    for col in col_names:
        out.loc[row,col] = find_significant(p=p_val.loc[row,col],val=Coef.loc[row,col])
        
os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM\Vars and OCM Meadian\PythonTex")
out.to_latex('Regression and Vars.tex',index=True,multirow=True,
             bold_rows=True,caption="Coefficients of the OCM in the Regression")

# **Yearly Univariate Analysis**

In [43]:
%%time
iterables = [Vars,list(Data.year.drop_duplicates()), ['High', 'Low','diff','p_value']]
col_index = pd.MultiIndex.from_product(iterables)
out_yearly = pd.DataFrame(index=OCM,columns=col_index)

iterables = [Vars,list(Data.year.drop_duplicates())]
col_index = pd.MultiIndex.from_product(iterables)
out_yearly_diff = pd.DataFrame(index=OCM,columns=col_index)


for ocm in OCM:     
        
    df = Data.copy()
    
    for year in range(1389,1398):
        df_year = df[df.year==year]
        meadian = df_year[ocm].describe()['50%']
        df_year['above_meadian'] = df_year[ocm]>meadian
        df_year = df_year[~pd.isnull(df_year.above_meadian)]
        
        for var in Vars:
        
            temp = df_year[~pd.isnull(df_year[var])]
            
            serie1 = temp[temp.above_meadian][var]
            high = np.round(np.mean(serie1),3)

            serie2 = temp[~temp.above_meadian][var]
            low = np.round(np.mean(serie2),3)

            (t,p) = ttest_ind(serie1,serie2,nan_policy='omit')

            diff = find_significant(p,np.round(high-low,3))

            out_yearly.loc[ocm,(var,year,)] = [high,low,diff,np.round(p,2)]
            out_yearly_diff.loc[ocm,(var,year)] = diff
            
            
out_yearly      
out_yearly_diff

C:\Users\Mahdi\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2362: PerformanceWarning: indexing past lexsort depth may impact performance.
  result = fn(*args, **kwargs)

Wall time: 42 s

                      marketcap                                    \
                           1389             1390             1391
sum_over1           -948656.954     -3210659.195       467218.913
sumfive            -1405470.147    -4328642.241*     -1477931.709
sumfour            -1514475.229     -4113515.33*     -3129553.704
sumthree            -1759271.56     -3875274.753     -3912857.988
sumtwo             -1495963.097    -4313927.204*   -7531929.961**
largest_owner      -1987070.033  -7252778.193***  -9572596.539***
first_second         309290.674     -3707641.246   -7845819.39***
first_sumtwofour    -355997.783  -7302936.083***  -7935006.113***
gini                 144782.544    -4341732.173*   -8408110.93***
herfindahl        -2353338.475*   -5994762.254**  -8504953.676***
sscl                -1851080.04  -7345608.064***  -9686171.017***
ssco                1478434.286   6395653.479***   8409390.127***
ssdl                -1851080.04  -7267971.374***  -9569178.105***
ssdo                1478434.286    6613965.05***      4480836.773
bzcl                -1260823.44  -7413784.348***              nan
bzco                1309830.314   7178377.605***  10447209.091***
bzdl                        nan              nan              nan

                                                                       \
                              1392             1393              1394
sum_over1              2268863.629       847775.807      -1684406.336
sumfive                -816863.586       363809.159      -2235639.075
sumfour                -755623.115     -5024009.887   -7996045.178***
sumthree              -1953286.702    -5546525.796*   -8393394.834***
sumtwo                -3661344.663   -7058428.401**   -8977464.669***
largest_owner     -10258425.336***   -8992794.16***  -10127150.334***
first_second       -8978267.538***  -9766197.901***  -10569716.021***
first_sumtwofour  -11092187.318***  -9976541.522***  -10497614.743***
gini                -8122930.695**  -8419448.462***   -9124652.533***
herfindahl          -8466725.716**   -7840755.422**    -9107515.85***
sscl                           nan              nan               nan
ssco               10426402.316***   9321138.471***   10585883.667***
ssdl                           nan              nan               nan
ssdo                9657324.741***    7186320.627**   10216329.132***
bzcl                           nan              nan               nan
bzco               12011366.495***   10455627.57***   11453319.365***
bzdl                           nan              nan               nan

                                                                        \
                              1395              1396              1397
sum_over1              2151959.954         -825902.1   52673103.118***
sumfive               -1237092.288        1746475.59     37766953.597*
sumfour                -6032192.23      -4243064.884        27953806.1
sumthree             -7746912.287*       -8985907.18     -10366799.599
sumtwo              -9442738.757**   -12866421.266**      -23463131.91
largest_owner     -11699667.242***    -14406420.14**    -35914403.053*
first_second      -11677722.669***  -20419378.961***  -67388855.343***
first_sumtwofour   -12768941.08***   -19837972.32***  -59641793.954***
gini               -10781307.855**  -17113706.873***   -42554555.586**
herfindahl         -10652002.412**   -12419345.625**    -34566527.034*
sscl                           nan               nan               nan
ssco               12462843.702***    14819184.383**     39686355.132*
ssdl                           nan               nan               nan
ssdo               12821785.741***    14060966.418**      38295795.02*
bzcl                           nan               nan               nan
bzco               14012646.077***   18183726.575***    50750753.703**
bzdl                           nan               nan               nan

                  payout  ...      LNTA     LNQ                             \
                    1389  ...      1397    1389    1390     1391      1392
sum_over1          0.051  ...  1.002***   0.135   0.011  0.201**   0.29***
sumfive            0.051  ...  0.931***   0.113    0.07  0.201**  0.229***
sumfour            0.053  ...  0.837***  0.151*   0.068  0.196**   0.206**
sumthree           0.061  ...  0.664***   0.119   0.107   0.185*   0.198**
sumtwo             0.049  ...  0.454***   0.077   0.041   0.183*   0.204**
largest_owner      0.047  ...     0.244   0.017   0.021    0.107    0.152*
first_second       0.017  ...   -0.44**  -0.026  -0.075    0.012    -0.038
first_sumtwofour  -0.029  ...    -0.271  -0.067  -0.076   -0.031    -0.027
gini                0.05  ...    -0.091  -0.014    0.06    0.046    -0.009
herfindahl         0.061  ...   0.356**   0.069   0.015    0.144    0.18**
sscl               0.039  ...       nan   0.031   0.029    0.121       nan
ssco              -0.074  ...    -0.286  -0.121  -0.076   -0.073  -0.202**
ssdl               0.039  ...       nan   0.031  -0.014    0.147       nan
ssdo              -0.074  ...    -0.256  -0.121  -0.122   -0.044   -0.21**
bzcl              -0.013  ...       nan   0.025  -0.006      nan       nan
bzco              -0.063  ...    -0.148  -0.026  -0.005   -0.019   -0.158*
bzdl                 nan  ...       nan     nan     nan      nan       nan


                    1393      1394    1395       1396     1397
sum_over1          0.078   0.208**   0.135    -0.25**  -0.184*
sumfive            0.064   0.221**   0.147  -0.307***   -0.135
sumfour             0.08   0.183**  0.171*  -0.322***   -0.084
sumthree           0.087     0.112  0.162*   -0.249**   -0.127
sumtwo             0.062     0.119   0.109    -0.202*   -0.022
largest_owner     -0.032     0.019   0.048    -0.201*    0.004
first_second      -0.129  -0.184**  -0.18*   -0.253**    0.108
first_sumtwofour  -0.038    -0.132  -0.138  -0.289***    0.069
gini              -0.085   -0.21**  -0.141  -0.307***    0.085
herfindahl         0.043    0.147*   0.102     -0.124    0.032
sscl                 nan       nan     nan        nan      nan
ssco              -0.005    -0.093   -0.16      0.169   -0.025
ssdl                 nan       nan     nan        nan      nan
ssdo               0.004    -0.077   -0.16     0.181*   -0.025
bzcl                 nan       nan     nan        nan      nan
bzco              -0.034    -0.087  -0.157     0.216*   -0.017
bzdl                 nan       nan     nan        nan      nan

[17 rows x 144 columns]

In [52]:
out_yearly[('MTB',1397)]
out_yearly_diff[('payout',)]

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

                    High     Low    diff p_value
sum_over1          21.99    22.2   -0.21    0.97
sumfive           22.677  21.496   1.181    0.82
sumfour           23.111  21.038   2.073    0.68
sumthree          22.851  21.317   1.534    0.76
sumtwo            24.903  19.209   5.694    0.26
largest_owner     24.625  19.522   5.103    0.32
first_second      26.745  17.419  9.326*    0.07
first_sumtwofour  23.899  20.301   3.598    0.48
gini              24.572  19.604   4.968    0.33
herfindahl        26.012  18.156   7.856    0.12
sscl                 NaN  22.095     nan     NaN
ssco              18.416  25.201  -6.785    0.19
ssdl                 NaN  22.095     nan     NaN
ssdo              19.197  24.679  -5.482    0.28
bzcl                 NaN  22.095     nan     NaN
bzco              20.655  23.113  -2.458    0.64
bzdl                 NaN  22.095     nan     NaN

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)

,1389,1390,1391,1392,1393,1394,1395,1396,1397
OCM,,,,,,,,,
Sum_over1,0.051,0.048,0.124***,0.163***,0.111**,0.363,0.286***,0.21***,0.263***
Sumfive,0.051,0.063,0.096**,0.167***,0.115**,0.357,0.278***,0.185***,0.245***
Sumfour,0.053,0.069,0.104**,0.16***,0.128**,0.347,0.245***,0.165**,0.224***
Sumthree,0.061,0.06,0.101**,0.158***,0.121**,0.297,0.225***,0.143**,0.208***
Sumtwo,0.049,0.042,0.057,0.067,0.064,0.187,0.165***,0.204***,0.183***
Largest Owner,0.047,0.021,0.025,0.07,0.019,0.146,0.078,0.157**,0.123**
First/Second,0.017,0.026,-0.035,-0.004,-0.049,0.143,-0.043,0.043,-0.029
First/Sumtwofour,-0.029,0.036,-0.046,-0.018,-0.053,0.111,-0.043,0.043,-0.031
Gini,0.05,0.147**,0.027,0.08*,0.007,0.248,0.034,0.084,0.01
Herfindahl,0.061,0.057,0.054,0.106**,0.068,0.174,0.143***,0.171**,0.145**
SSCL,0.039,0.026,0.026,nan,nan,nan,nan,nan,nan
SSCO,-0.074,-0.046,-0.091*,-0.074,-0.029,-0.124,-0.089*,-0.189***,-0.144**
SSDL,0.039,0.019,0.035,nan,nan,nan,nan,nan,nan
SSDO,-0.074,-0.035,-0.082*,-0.075,-0.044,-0.086,-0.082,-0.188***,-0.137**
BZCL,-0.013,0.078,nan,nan,nan,nan,nan,nan,nan
BZCO,-0.063,-0.09,-0.026,-0.063,0.029,-0.056,-0.076,-0.143**,-0.085
BZDL,nan,nan,nan,nan,nan,nan,nan,nan,nan

## Latex Output

In [45]:
index = ['Sum_over1','Sumfive','Sumfour','Sumthree','Sumtwo','Largest Owner','First/Second',
         'First/Sumtwofour', 'Gini','Herfindahl','SSCL', 'SSCO', 'SSDL', 'SSDO', 'BZCL', 'BZCO', 'BZDL']

out_yearly_diff['OCM'] = index
out_yearly_diff.set_index('OCM',inplace=True)

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Codes\Dividend and OCM\Vars, OCM, Summary Through Time\PythonTex")
for var in Vars:
    temp = out_yearly_diff[(var,)]
    
    file_name = var+'_Yearly.tex'
    caption = 'Differences in '+var+' for Two Groups of Above and Below Meadian'
    
    temp.to_latex(file_name,index=True,multirow=True,
             bold_rows=True,caption=caption)

C:\Users\Mahdi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2858: PerformanceWarning: indexing past lexsort depth may impact performance.
  raw_cell, store_history, silent, shell_futures)