In [1]:
## Loading Libraries
import pandas as pd
import numpy as np
import sys
import jdatetime as jd
import os
import pickle
from scipy import stats
# import power_index_calculator as px
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Loading Data

In [2]:
## Loading DATA
os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
df = pd.read_csv("data_owenership97_blnc98.csv",index_col=0)
OC_list = ['Largest_Owner','First_Second','First_Sumtwofour','Sumfive',
           'Gini','Herfindhal','SSCL','SSCO','SSDL','SSDO','BZCL','BZCO','BZDL']

## Summary Stat of Data

In [3]:
df[OC_list].describe()

,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,SSCL,SSCO,SSDL,SSDO,BZCL,BZCO,BZDL
count,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,595.000000,595.000000,605.000000,605.000000,605.000000
mean,51.590182,8.668201,6.351044,72.329438,0.570338,0.363948,0.722935,inf,0.734562,0.133156,0.775352,0.102388,0.847912
std,25.570321,14.791023,12.476705,22.381365,0.292798,0.269813,0.340039,NaN,0.334095,0.216318,0.336476,0.201890,0.279722
min,3.300000,1.000000,0.333333,4.860000,0.000000,0.001612,0.033779,0.000000,0.034106,0.000000,0.034103,0.000000,0.060942
25%,32.550000,1.343984,1.000000,59.450000,0.402205,0.159124,0.387573,0.000000,0.398958,0.000000,0.469759,0.000000,0.900000
50%,50.990000,2.717549,1.597795,77.140000,0.636136,0.302100,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
75%,68.290000,7.838612,5.069212,89.970000,0.798753,0.489934,1.000000,0.230602,1.000000,0.206133,1.000000,0.102258,1.000000
max,99.990000,96.000000,92.660000,100.000000,0.978646,0.999800,1.000000,inf,1.000000,0.948917,1.000000,0.947457,1.000000

In [9]:
df[np.logical_and(~pd.isnull(df.book_value),~pd.isnull(df.sum_over1))]

,Symbol,Id_tse,sum_over1,Num_holders,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,...,BZCL,BZCO,BZDL,Tot_asset,Tot_lib,Capital,Equity_at_year_end,Debt_Equity,Debt_Equity_normal,book_value
2,آ س پ,1.761747e+16,89.20,5.0,40.26,1.963902,0.912925,89.20,0.464462,0.236507,...,0.521370,0.105370,0.636360,1465029.0,518844.0,800000.0,946185.0,1465029.0,946185.0,946185.0
5,آریان,6.506180e+15,77.98,26.0,10.38,1.119741,0.450521,38.32,0.401057,0.039486,...,0.111966,0.214949,0.143287,27829680.0,2803931.0,19817375.0,25025749.0,27829680.0,24332141.0,25025749.0
17,ارفع,5.926670e+16,95.63,8.0,43.69,2.131220,1.056590,88.56,0.637860,0.266236,...,0.613010,0.056740,0.619570,20243835.0,7024400.0,6000000.0,13219435.0,20243835.0,7219435.0,13219435.0
20,اعتلا,3.677316e+16,89.05,4.0,54.57,1.819607,1.582657,89.05,0.692607,0.388741,...,1.000000,0.000000,1.000000,1690056.0,109279.0,600000.0,1580777.0,1690056.0,1140777.0,1580777.0
22,افرا,5.279290e+16,97.18,6.0,30.56,1.528000,0.509503,95.16,0.388640,0.215854,...,0.500000,0.000000,0.500000,1334792.0,459833.0,625000.0,874959.0,1334792.0,806209.0,874959.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,کیمیا,2.781484e+16,77.14,5.0,43.40,2.155986,1.337442,77.14,0.665025,0.240523,...,0.948813,0.039738,1.000000,1267241.0,406487.0,230400.0,860754.0,1267241.0,710994.0,860754.0
600,گنگین,5.947011e+16,99.25,2.0,79.25,3.962500,3.962500,99.25,0.596977,0.668056,...,1.000000,0.000000,1.000000,13914324.0,7466542.0,3000000.0,6447782.0,13914324.0,3957782.0,6447782.0
601,گوهران,6.501880e+16,94.14,1.0,94.14,1.000000,1.000000,94.14,0.000000,0.886234,...,1.000000,0.000000,1.000000,4293982.0,466899.0,2000000.0,3827083.0,4293982.0,3027083.0,3827083.0
603,گکوثر,6.659911e+16,87.82,4.0,46.00,1.380138,1.099952,87.82,0.586275,0.326294,...,0.792582,0.137922,1.000000,404599.0,192500.0,110000.0,212099.0,404599.0,122999.0,212099.0
604,گکیش,4.466576e+16,68.25,1.0,68.25,1.000000,1.000000,68.25,0.000000,0.465806,...,1.000000,0.000000,1.000000,99050.0,10521.0,64000.0,88529.0,99050.0,78929.0,88529.0

## Wilcoxon Test

In [4]:
out = pd.DataFrame()
out_list = list()

for i in range(len(OC_list)):
    x = df[OC_list[i]]
    
    for j in range(len(OC_list)):
        y = df[OC_list[j]]
        
        zipped = [ (a,b) for a,b in zip(x,y) if a is not np.nan and b is not np.nan]
        x =  [a for a,b in zipped]
        y =  [b for a,b in zipped]

        w,p = stats.wilcoxon(x=x,y=y)
        
        if p<0.05 and p>0.01:
            out.loc[OC_list[j],OC_list[i]] = str(np.round(w,3))+'*'
        elif p<0.01:
            out.loc[OC_list[j],OC_list[i]] = str(np.round(w,3))+'**'
        else:
            out.loc[OC_list[j],OC_list[i]] = str(np.round(w,3))
        
        out_list.append([OC_list[j],OC_list[i],w,p])
        
out

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
out.to_csv('Wilcoxon_p.csv')

C:\Users\Mahdi\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2882: RuntimeWarning: invalid value encountered in greater
  r_plus = np.sum((d > 0) * r, axis=0)
C:\Users\Mahdi\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2883: RuntimeWarning: invalid value encountered in less
  r_minus = np.sum((d < 0) * r, axis=0)
C:\Users\Mahdi\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2865: RuntimeWarning: invalid value encountered in subtract
  d = x - y

,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,SSCL,SSCO,SSDL,SSDO,BZCL,BZCO,BZDL
Largest_Owner,0.0**,0.0**,0.0**,31.5**,0.0**,0.0**,0.0**,8970.0**,0.0**,0.0**,0.0**,0.0**,0.0**
First_Second,0.0**,0.0**,0.0**,0.0**,0.0**,0.0**,0.0**,8970.0**,0.0**,0.0**,0.0**,0.0**,3.0**
First_Sumtwofour,0.0**,0.0**,0.0**,0.0**,76.0**,0.0**,0.0**,9014.0**,0.0**,43.0**,0.0**,68.0**,3.0**
Sumfive,31.5**,0.0**,0.0**,0.0**,0.0**,0.0**,0.0**,8970.0**,0.0**,0.0**,0.0**,0.0**,0.0**
Gini,0.0**,0.0**,76.0**,0.0**,0.0**,34778.0**,55364.0**,16140.0**,50848.0**,7987.0**,38324.0**,6760.0**,16406.0**
Herfindhal,0.0**,0.0**,0.0**,0.0**,34778.0**,0.0**,97.0**,48225.0**,93.0**,38719.0**,149.0**,33179.0**,92.0**
SSCL,0.0**,0.0**,0.0**,0.0**,55364.0**,97.0**,0.0**,21593.0**,6195.0**,12050.0**,6146.0**,11036.0**,408.0**
SSCO,8970.0**,8970.0**,9014.0**,8970.0**,16140.0**,48225.0**,21593.0**,0.0**,20250.0**,8861.0**,18215.0**,9017.0**,11533.0**
SSDL,0.0**,0.0**,0.0**,0.0**,50848.0**,93.0**,6195.0**,20250.0**,0.0**,11975.0**,5920.0**,9993.0**,399.0**
SSDO,0.0**,0.0**,43.0**,0.0**,7987.0**,38719.0**,12050.0**,8861.0**,11975.0**,0.0**,8789.0**,9894.0**,2201.0**
BZCL,0.0**,0.0**,0.0**,0.0**,38324.0**,149.0**,6146.0**,18215.0**,5920.0**,8789.0**,0.0**,8950.0**,60.0**
BZCO,0.0**,0.0**,68.0**,0.0**,6760.0**,33179.0**,11036.0**,9017.0**,9993.0**,9894.0**,8950.0**,0.0**,3000.0**
BZDL,0.0**,3.0**,3.0**,0.0**,16406.0**,92.0**,408.0**,11533.0**,399.0**,2201.0**,60.0**,3000.0**,0.0**

## Spearman Correlation Rank Test

In [5]:
out = pd.DataFrame()
out_list = list()

for i in range(len(OC_list)):
    x = df[OC_list[i]]
    
    for j in range(len(OC_list)):
        y = df[OC_list[j]]
        
        zipped = [ (a,b) for a,b in zip(x,y) if a is not np.nan and b is not np.nan]
        x =  [a for a,b in zipped]
        y =  [b for a,b in zipped]

        rho,p = stats.spearmanr(x,y,nan_policy='omit')
        if p<0.05 and p>0.01:
            out.loc[OC_list[j],OC_list[i]] = str(np.round(rho,4))+'*'
        elif p<0.01:
            out.loc[OC_list[j],OC_list[i]] = str(np.round(rho,4))+'**'
        else:
            out.loc[OC_list[j],OC_list[i]] = str(np.round(rho,4))
        
        out_list.append([OC_list[j],OC_list[i],w,p])
        
out

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
out.to_csv('Spearman_p.csv')

,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,SSCL,SSCO,SSDL,SSDO,BZCL,BZCO,BZDL
Largest_Owner,1.0**,0.3657**,0.5764**,0.732**,0.3726**,0.9815**,0.9197**,-0.8508**,0.9154**,-0.8437**,0.9001**,-0.8467**,0.6656**
First_Second,0.3657**,1.0**,0.9154**,0.035,0.9235**,0.2822**,0.4399**,-0.3191**,0.4331**,-0.3205**,0.4712**,-0.4175**,0.4517**
First_Sumtwofour,0.5764**,0.9154**,1.0**,0.1376**,0.8683**,0.4892**,0.639**,-0.4508**,0.6264**,-0.4444**,0.6774**,-0.5925**,0.7176**
Sumfive,0.732**,0.035,0.1376**,1.0**,0.0842*,0.8223**,0.6137**,-0.7017**,0.594**,-0.6735**,0.5539**,-0.588**,0.2817**
Gini,0.3726**,0.9235**,0.8683**,0.0842*,1.0**,0.3068**,0.446**,-0.3369**,0.4369**,-0.3319**,0.4638**,-0.423**,0.4204**
Herfindhal,0.9815**,0.2822**,0.4892**,0.8223**,0.3068**,1.0**,0.8846**,-0.8581**,0.8789**,-0.848**,0.8518**,-0.8226**,0.5941**
SSCL,0.9197**,0.4399**,0.639**,0.6137**,0.446**,0.8846**,1.0**,-0.9161**,1.0**,-0.9067**,0.9835**,-0.9186**,0.7399**
SSCO,-0.8508**,-0.3191**,-0.4508**,-0.7017**,-0.3369**,-0.8581**,-0.9161**,1.0**,-0.9225**,0.993**,-0.8785**,0.9164**,-0.4795**
SSDL,0.9154**,0.4331**,0.6264**,0.594**,0.4369**,0.8789**,1.0**,-0.9225**,1.0**,-0.9063**,0.9829**,-0.9194**,0.7262**
SSDO,-0.8437**,-0.3205**,-0.4444**,-0.6735**,-0.3319**,-0.848**,-0.9067**,0.993**,-0.9063**,1.0**,-0.8702**,0.909**,-0.4551**
BZCL,0.9001**,0.4712**,0.6774**,0.5539**,0.4638**,0.8518**,0.9835**,-0.8785**,0.9829**,-0.8702**,1.0**,-0.9276**,0.776**
BZCO,-0.8467**,-0.4175**,-0.5925**,-0.588**,-0.423**,-0.8226**,-0.9186**,0.9164**,-0.9194**,0.909**,-0.9276**,1.0**,-0.6365**
BZDL,0.6656**,0.4517**,0.7176**,0.2817**,0.4204**,0.5941**,0.7399**,-0.4795**,0.7262**,-0.4551**,0.776**,-0.6365**,1.0**