In [1]:
## Loading Libraries
import pandas as pd
import numpy as np
import sys
import jdatetime as jd
import os
import pickle
from scipy import stats
# import power_index_calculator as px
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Loading Data

In [2]:
df[df.sum_over1>=90]

NameError: name 'df' is not defined

In [46]:
## Loading DATA

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data\Avergae day Volume - yearly")
temp = pd.read_csv("list_of_total_average6.csv",index_col=0)
    
os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
df = pd.read_csv("data_owenership98_blnc98.csv",index_col=0)

In [47]:
os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
df = pd.read_csv("data_owenership98_blnc98.csv",index_col=0)
print('Number of Observation is: ',len(df),'\n')

## Filtering Data
theta_sum1 = 90
theta_holder = 3


filtered = df[df.sum_over1>=theta_sum1]
df = df[df.sum_over1<=theta_sum1]
print(len(filtered),' is deleted becaause their sum_above1% is equalt to or more than ',theta_sum1,'%')

filtered = df[df.Num_holders<=theta_holder]
df = df[df.Num_holders>theta_holder]
print(len(filtered),' is deleted becaause their number of holder is less or equal than ',theta_holder)

print('\nNumber of remained Observation is: ',len(df))

Number of Observation is:  722

122  is deleted becaause their sum_above1% is equalt to or more than  90 %
251  is deleted becaause their number of holder is less or equal than  3

Number of remained Observation is:  282

In [48]:
df.loc[df['SSCO']==np.inf,'SSCO'] = np.nan
df.loc[df['Num_holders']==1,'First_Second'] = np.nan
df.loc[df['Num_holders']<4,'First_Sumtwofour'] = np.nan
df.loc[df['Num_holders']==1,'Gini'] = np.nan
df.loc[df['Num_holders']<5,'Sumfive'] = np.nan

In [49]:
df[df.First_Sumtwofour>10]

,Symbol,Id_tse,sum_over1,Num_holders,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,...,BZCL,BZCO,BZDL,Tot_asset,Tot_lib,Capital,Equity_at_year_end,Debt_Equity,Debt_Equity_normal,book_value
18,اطلس,1.142794e+16,80.34,4.0,73.12,19.343915,10.127424,NaN,0.900838,0.536711,...,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,اوان,6.984714e+16,60.39,4.0,56.91,46.647541,16.353448,NaN,0.924712,0.324280,...,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,بهپاک,1.274673e+16,72.76,4.0,66.22,29.043860,10.125382,NaN,0.882719,0.439939,...,1.0,0.0,1.0,3606540.0,2511748.0,500000.0,1094792.0,3606540.0,894792.0,1094792.0
187,دشیمی,3.360321e+16,84.00,4.0,78.07,27.982079,13.165261,NaN,0.918175,0.610786,...,1.0,0.0,1.0,1711380.0,1245460.0,255000.0,465920.0,1711380.0,346070.0,465920.0
261,سهگمت,4.128452e+16,78.56,5.0,70.35,27.057692,10.740458,78.56,0.879837,0.496655,...,1.0,0.0,1.0,2837824.0,1581918.0,502900.0,1255906.0,2837824.0,1031577.0,1255906.0
305,شوینده,3.493306e+15,81.02,4.0,76.69,43.573864,17.711316,NaN,0.932856,0.588776,...,1.0,0.0,1.0,3999403.0,410110.0,1000000.0,3589293.0,3999403.0,1939292.0,3589293.0
311,شپمچا,4.434510e+16,85.07,4.0,81.30,59.343066,21.564987,NaN,0.942322,0.661445,...,1.0,0.0,1.0,1478731.0,1101628.0,30000.0,377103.0,1478731.0,-198510.0,377103.0
346,غویتا,3.784279e+16,84.81,4.0,77.48,20.827957,10.570259,NaN,0.906143,0.602480,...,1.0,0.0,1.0,4154136.0,2040958.0,600000.0,2113178.0,4154136.0,1067160.0,2113178.0
367,فباهنر,6.677202e+16,81.84,4.0,77.64,40.863158,18.485714,NaN,0.938335,0.603424,...,1.0,0.0,1.0,6965882.0,4854284.0,1125000.0,2111598.0,6965882.0,1409598.0,2111598.0
582,چدن,1.232952e+16,73.55,4.0,69.82,50.230216,18.718499,NaN,0.934920,0.487951,...,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Summary Stat of Data

In [50]:
OC_list = ['Largest_Owner','First_Second','First_Sumtwofour','Sumfive',
           'Gini','Herfindhal','SSCL','SSCO','SSDL','SSDO','BZCL','BZCO','BZDL']
df[OC_list].describe()

,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,SSCL,SSCO,SSDL,SSDO,BZCL,BZCO,BZDL
count,282.000000,282.000000,282.000000,199.000000,282.000000,282.000000,282.000000,272.000000,275.000000,275.000000,282.000000,282.000000,282.000000
mean,39.136631,5.499447,2.699731,64.223216,0.618824,0.223606,0.591739,0.192085,0.606980,0.186982,0.650833,0.161218,0.747217
std,19.178589,7.870683,3.229442,17.917631,0.191532,0.151617,0.344782,0.201166,0.340421,0.199677,0.363882,0.204050,0.318760
min,2.600000,1.000000,0.333333,20.230000,0.076027,0.001532,0.026420,0.000000,0.026669,0.000000,0.026489,0.000000,0.061563
25%,21.372500,1.539105,0.775866,50.300000,0.495038,0.099214,0.249247,0.000000,0.265625,0.000000,0.279678,0.000000,0.478775
50%,39.965000,2.509329,1.477448,68.250000,0.623910,0.205743,0.550309,0.164604,0.578632,0.157882,0.810043,0.046917,1.000000
75%,52.217500,5.747868,3.239208,78.920000,0.783520,0.297281,1.000000,0.294053,1.000000,0.283744,1.000000,0.282881,1.000000
max,81.300000,59.343066,21.564987,89.990000,0.942322,0.661445,1.000000,0.923518,1.000000,0.922627,1.000000,0.923344,1.000000

In [25]:
df[np.logical_and(~pd.isnull(df.book_value),~pd.isnull(df.sum_over1))]

,Symbol,Id_tse,sum_over1,Num_holders,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,...,BZCL,BZCO,BZDL,Tot_asset,Tot_lib,Capital,Equity_at_year_end,Debt_Equity,Debt_Equity_normal,book_value
2,آ س پ,1.761747e+16,79.08,5.0,40.26,2.689379,1.083132,79.08,0.529274,0.210784,...,0.617099,0.234059,1.000000,1465029.0,518844.0,800000.0,946185.0,1465029.0,946185.0,946185.0
5,آریان,6.506180e+15,67.90,21.0,10.38,1.108974,0.479446,36.93,0.420619,0.036699,...,0.112467,0.313345,0.164849,27829680.0,2803931.0,19817375.0,25025749.0,27829680.0,24332141.0,25025749.0
22,افرا,5.279290e+16,89.23,5.0,27.21,1.360500,0.453500,89.23,0.282304,0.194446,...,0.444208,0.076744,0.500000,1334792.0,459833.0,625000.0,874959.0,1334792.0,806209.0,874959.0
43,برکت,3.455724e+16,89.25,4.0,78.50,13.149079,7.302326,89.25,0.866293,0.620932,...,1.000000,0.000000,1.000000,11645928.0,6903657.0,3400000.0,4742271.0,11645928.0,4209434.0,4742271.0
48,بموتو,2.208688e+16,79.07,4.0,42.68,2.184237,1.172850,79.07,0.496986,0.235340,...,0.804572,0.144047,1.000000,5565966.0,2746561.0,680400.0,2819405.0,5565966.0,1458605.0,2819405.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,کچاد,1.802780e+16,80.49,6.0,39.26,2.286546,1.048891,78.98,0.581414,0.204909,...,0.565833,0.219819,0.750000,98882021.0,26036825.0,33500000.0,72845196.0,98882021.0,49395196.0,72845196.0
641,کگاز,6.234680e+16,76.84,5.0,50.99,3.202889,2.051911,76.84,0.739654,0.290429,...,1.000000,0.000000,1.000000,1935303.0,1126184.0,450000.0,809119.0,1935303.0,606619.0,809119.0
644,کی بی سی,6.297732e+16,88.01,4.0,76.07,8.713631,6.371022,88.01,0.874635,0.586809,...,1.000000,0.000000,1.000000,2501153.0,1866691.0,240000.0,634462.0,2501153.0,771262.0,634462.0
647,کیمیا,2.781484e+16,73.79,5.0,40.90,2.031793,1.284144,73.79,0.668790,0.219216,...,0.837944,0.128431,1.000000,1267241.0,406487.0,230400.0,860754.0,1267241.0,710994.0,860754.0
652,گکوثر,6.659911e+16,79.74,3.0,46.00,1.425914,1.363367,79.74,0.558315,0.315890,...,0.978808,0.018608,1.000000,404599.0,192500.0,110000.0,212099.0,404599.0,122999.0,212099.0

## Wilcoxon Test

In [51]:
out = pd.DataFrame()
out_list = list()

for i in range(len(OC_list)-1):
    x = df[OC_list[i]]
    
    for j in range(1,len(OC_list)):
        y = df[OC_list[j]]
        
        zipped = [ (a,b) for a,b in zip(x,y) if a is not np.nan and b is not np.nan]
        x =  [a for a,b in zipped]
        y =  [b for a,b in zipped]

        w,p = stats.wilcoxon(x=x,y=y)
        if j>i:
            if p<0.05 and p>0.01:
                out.loc[OC_list[j],OC_list[i]] = str(np.round(w,3))+'*'
            elif p<0.01:
                out.loc[OC_list[j],OC_list[i]] = str(np.round(w,3))+'**'
            else:
                out.loc[OC_list[j],OC_list[i]] = str(np.round(w,3))

            out_list.append([OC_list[j],OC_list[i],w,p])
        else:
            out.loc[OC_list[j],OC_list[i]] = ''
        
out

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
out.to_csv('Wilcoxon.csv')

C:\Users\Mahdi\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2882: RuntimeWarning: invalid value encountered in greater
  r_plus = np.sum((d > 0) * r, axis=0)
C:\Users\Mahdi\Anaconda3\lib\site-packages\scipy\stats\morestats.py:2883: RuntimeWarning: invalid value encountered in less
  r_minus = np.sum((d < 0) * r, axis=0)

ValueError: zero_method 'wilcox' and 'pratt' do not work if the x - y is zero for all elements.

## Spearman Correlation Rank Test

In [52]:
out = pd.DataFrame()
out_list = list()

for i in range(len(OC_list)-1):
    x = df[OC_list[i]]
    
    for j in range(1,len(OC_list)):
        y = df[OC_list[j]]
        
        zipped = [ (a,b) for a,b in zip(x,y) if a is not np.nan and b is not np.nan]
        x =  [a for a,b in zipped]
        y =  [b for a,b in zipped]
        
        if j>i:
            rho,p = stats.spearmanr(x,y,nan_policy='omit')
            if p<0.05 and p>0.01:
                out.loc[OC_list[j],OC_list[i]] = str(np.round(rho,4))+'*'
            elif p<0.01:
                out.loc[OC_list[j],OC_list[i]] = str(np.round(rho,4))+'**'
            else:
                out.loc[OC_list[j],OC_list[i]] = str(np.round(rho,4))

            out_list.append([OC_list[j],OC_list[i],w,p])
        else:
            out.loc[OC_list[j],OC_list[i]] = ''
out

os.chdir(r"C:\Users\Mahdi\OneDrive\Master Thesis\Data")
out.to_csv('Spearman.csv')

,Largest_Owner,First_Second,First_Sumtwofour,Sumfive,Gini,Herfindhal,SSCL,SSCO,SSDL,SSDO,BZCL,BZCO
First_Second,0.8037**,,,,,,,,,,,
First_Sumtwofour,0.8668**,0.9607**,,,,,,,,,,
Sumfive,0.6969**,0.213**,0.2585**,,,,,,,,,
Gini,0.8804**,0.8507**,0.9391**,0.3606**,,,,,,,,
Herfindhal,0.9766**,0.6853**,0.7611**,0.8183**,0.8046**,,,,,,,
SSCL,0.98**,0.8119**,0.87**,0.6342**,0.8751**,0.9421**,,,,,,
SSCO,-0.8592**,-0.5943**,-0.6295**,-0.7629**,-0.6836**,-0.902**,-0.8594**,,,,,
SSDL,0.978**,0.8042**,0.8634**,0.5925**,0.8682**,0.9374**,0.9999**,-0.8716**,,,,
SSDO,-0.8674**,-0.5903**,-0.626**,-0.7411**,-0.6815**,-0.9035**,-0.8675**,0.9991**,-0.8672**,,,
BZCL,0.9581**,0.8632**,0.9106**,0.5454**,0.894**,0.9009**,0.9842**,-0.8158**,0.9831**,-0.8206**,,
BZCO,-0.889**,-0.7287**,-0.7649**,-0.625**,-0.7874**,-0.8825**,-0.9038**,0.9159**,-0.9135**,0.9131**,-0.8979**,
BZDL,0.8036**,0.8195**,0.8758**,0.3727**,0.8126**,0.7125**,0.835**,-0.5177**,0.8217**,-0.5024**,0.8707**,-0.6725**